# Generated by Django 4.0.1 on 2022-02-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'phone_number'), name='unique_email_phone'),
        ),
    ]
