version: '3.8'

networks:
  static:
    ipam:
      driver: default
      config:
      - subnet: 172.23.1.0/16

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 8000
    environment:
      - ENV=DEV
      - PGHOST=172.23.1.102
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    networks:
      static:
        ipv4_address: 172.23.1.100
    depends_on:
      - db

  frontend:
    stdin_open: true
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      static:
        ipv4_address: 172.23.1.101
    depends_on:
      - backend

  db:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    networks:
      static:
        ipv4_address: 172.23.1.102
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  reverse_proxy:
    build: ./nginx
    ports:
      - 81:80
    networks:
      static:
        ipv4_address: 172.23.1.103
    depends_on:
      - backend
      - frontend
  
