# Generated by Django 4.0.1 on 2022-03-17 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobtype'),
        ),
    ]
