# Generated by Django 4.0.1 on 2022-03-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_worker_user'),
        ('jobs', '0002_alter_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerJobTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField(default=0)),
                ('end_time', models.BigIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.worker')),
            ],
        ),
    ]
