# Generated by Django 4.0.1 on 2022-03-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_workerjobtimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtype',
            name='available',
        ),
        migrations.AddField(
            model_name='jobtype',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
